/*
3gpp-as-session-with-qos

API for setting us an AS session with required QoS. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package assessionwithqos

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
	"strings"
)

// Linger please
var (
	_ _context.Context
)

type AsSessionWithQoSAPISubscriptionLevelPUTOperationApi interface {

	/*
	ScsAsIdSubscriptionsSubscriptionIdPut Updates/replaces an existing subscription resource

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @param scsAsId Identifier of the SCS/AS
	 @param subscriptionId Identifier of the subscription resource
	 @return ApiScsAsIdSubscriptionsSubscriptionIdPutRequest
	*/
	ScsAsIdSubscriptionsSubscriptionIdPut(ctx _context.Context, scsAsId string, subscriptionId string) ApiScsAsIdSubscriptionsSubscriptionIdPutRequest

	// ScsAsIdSubscriptionsSubscriptionIdPutExecute executes the request
	//  @return AsSessionWithQoSSubscription
	ScsAsIdSubscriptionsSubscriptionIdPutExecute(r ApiScsAsIdSubscriptionsSubscriptionIdPutRequest) (AsSessionWithQoSSubscription, *_nethttp.Response, error)
}

// AsSessionWithQoSAPISubscriptionLevelPUTOperationApiService AsSessionWithQoSAPISubscriptionLevelPUTOperationApi service
type AsSessionWithQoSAPISubscriptionLevelPUTOperationApiService service

type ApiScsAsIdSubscriptionsSubscriptionIdPutRequest struct {
	ctx _context.Context
	ApiService AsSessionWithQoSAPISubscriptionLevelPUTOperationApi
	scsAsId string
	subscriptionId string
	asSessionWithQoSSubscription *AsSessionWithQoSSubscription
}

// Parameters to update/replace the existing subscription
func (r ApiScsAsIdSubscriptionsSubscriptionIdPutRequest) AsSessionWithQoSSubscription(asSessionWithQoSSubscription AsSessionWithQoSSubscription) ApiScsAsIdSubscriptionsSubscriptionIdPutRequest {
	r.asSessionWithQoSSubscription = &asSessionWithQoSSubscription
	return r
}

func (r ApiScsAsIdSubscriptionsSubscriptionIdPutRequest) Execute() (AsSessionWithQoSSubscription, *_nethttp.Response, error) {
	return r.ApiService.ScsAsIdSubscriptionsSubscriptionIdPutExecute(r)
}

/*
ScsAsIdSubscriptionsSubscriptionIdPut Updates/replaces an existing subscription resource

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param scsAsId Identifier of the SCS/AS
 @param subscriptionId Identifier of the subscription resource
 @return ApiScsAsIdSubscriptionsSubscriptionIdPutRequest
*/
func (a *AsSessionWithQoSAPISubscriptionLevelPUTOperationApiService) ScsAsIdSubscriptionsSubscriptionIdPut(ctx _context.Context, scsAsId string, subscriptionId string) ApiScsAsIdSubscriptionsSubscriptionIdPutRequest {
	return ApiScsAsIdSubscriptionsSubscriptionIdPutRequest{
		ApiService: a,
		ctx: ctx,
		scsAsId: scsAsId,
		subscriptionId: subscriptionId,
	}
}

// Execute executes the request
//  @return AsSessionWithQoSSubscription
func (a *AsSessionWithQoSAPISubscriptionLevelPUTOperationApiService) ScsAsIdSubscriptionsSubscriptionIdPutExecute(r ApiScsAsIdSubscriptionsSubscriptionIdPutRequest) (AsSessionWithQoSSubscription, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPut
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  AsSessionWithQoSSubscription
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AsSessionWithQoSAPISubscriptionLevelPUTOperationApiService.ScsAsIdSubscriptionsSubscriptionIdPut")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{scsAsId}/subscriptions/{subscriptionId}"
	localVarPath = strings.Replace(localVarPath, "{"+"scsAsId"+"}", _neturl.PathEscape(parameterToString(r.scsAsId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"subscriptionId"+"}", _neturl.PathEscape(parameterToString(r.subscriptionId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.asSessionWithQoSSubscription == nil {
		return localVarReturnValue, nil, reportError("asSessionWithQoSSubscription is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.asSessionWithQoSSubscription
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 411 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 413 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 415 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
