/*
3gpp-as-session-with-qos

API for setting us an AS session with required QoS. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package assessionwithqos

import (
	"encoding/json"
)

// UserPlaneEventReport struct for UserPlaneEventReport
type UserPlaneEventReport struct {
	Event UserPlaneEvent `json:"event"`
	AccumulatedUsage *AccumulatedUsage `json:"accumulatedUsage,omitempty"`
	// Identifies the IP flows that were sent during event subscription
	FlowIds *[]int32 `json:"flowIds,omitempty"`
	// The currently applied QoS reference. Applicable for event QOS_NOT_GUARANTEED or SUCCESSFUL_RESOURCES_ALLOCATION.
	AppliedQosRef *string `json:"appliedQosRef,omitempty"`
	// Contains the QoS Monitoring Reporting information
	QosMonReports *[]QosMonitoringReport `json:"qosMonReports,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UserPlaneEventReport UserPlaneEventReport

// NewUserPlaneEventReport instantiates a new UserPlaneEventReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserPlaneEventReport(event UserPlaneEvent) *UserPlaneEventReport {
	this := UserPlaneEventReport{}
	this.Event = event
	return &this
}

// NewUserPlaneEventReportWithDefaults instantiates a new UserPlaneEventReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserPlaneEventReportWithDefaults() *UserPlaneEventReport {
	this := UserPlaneEventReport{}
	return &this
}

// GetEvent returns the Event field value
func (o *UserPlaneEventReport) GetEvent() UserPlaneEvent {
	if o == nil {
		var ret UserPlaneEvent
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *UserPlaneEventReport) GetEventOk() (*UserPlaneEvent, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *UserPlaneEventReport) SetEvent(v UserPlaneEvent) {
	o.Event = v
}

// GetAccumulatedUsage returns the AccumulatedUsage field value if set, zero value otherwise.
func (o *UserPlaneEventReport) GetAccumulatedUsage() AccumulatedUsage {
	if o == nil || o.AccumulatedUsage == nil {
		var ret AccumulatedUsage
		return ret
	}
	return *o.AccumulatedUsage
}

// GetAccumulatedUsageOk returns a tuple with the AccumulatedUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPlaneEventReport) GetAccumulatedUsageOk() (*AccumulatedUsage, bool) {
	if o == nil || o.AccumulatedUsage == nil {
		return nil, false
	}
	return o.AccumulatedUsage, true
}

// HasAccumulatedUsage returns a boolean if a field has been set.
func (o *UserPlaneEventReport) HasAccumulatedUsage() bool {
	if o != nil && o.AccumulatedUsage != nil {
		return true
	}

	return false
}

// SetAccumulatedUsage gets a reference to the given AccumulatedUsage and assigns it to the AccumulatedUsage field.
func (o *UserPlaneEventReport) SetAccumulatedUsage(v AccumulatedUsage) {
	o.AccumulatedUsage = &v
}

// GetFlowIds returns the FlowIds field value if set, zero value otherwise.
func (o *UserPlaneEventReport) GetFlowIds() []int32 {
	if o == nil || o.FlowIds == nil {
		var ret []int32
		return ret
	}
	return *o.FlowIds
}

// GetFlowIdsOk returns a tuple with the FlowIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPlaneEventReport) GetFlowIdsOk() (*[]int32, bool) {
	if o == nil || o.FlowIds == nil {
		return nil, false
	}
	return o.FlowIds, true
}

// HasFlowIds returns a boolean if a field has been set.
func (o *UserPlaneEventReport) HasFlowIds() bool {
	if o != nil && o.FlowIds != nil {
		return true
	}

	return false
}

// SetFlowIds gets a reference to the given []int32 and assigns it to the FlowIds field.
func (o *UserPlaneEventReport) SetFlowIds(v []int32) {
	o.FlowIds = &v
}

// GetAppliedQosRef returns the AppliedQosRef field value if set, zero value otherwise.
func (o *UserPlaneEventReport) GetAppliedQosRef() string {
	if o == nil || o.AppliedQosRef == nil {
		var ret string
		return ret
	}
	return *o.AppliedQosRef
}

// GetAppliedQosRefOk returns a tuple with the AppliedQosRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPlaneEventReport) GetAppliedQosRefOk() (*string, bool) {
	if o == nil || o.AppliedQosRef == nil {
		return nil, false
	}
	return o.AppliedQosRef, true
}

// HasAppliedQosRef returns a boolean if a field has been set.
func (o *UserPlaneEventReport) HasAppliedQosRef() bool {
	if o != nil && o.AppliedQosRef != nil {
		return true
	}

	return false
}

// SetAppliedQosRef gets a reference to the given string and assigns it to the AppliedQosRef field.
func (o *UserPlaneEventReport) SetAppliedQosRef(v string) {
	o.AppliedQosRef = &v
}

// GetQosMonReports returns the QosMonReports field value if set, zero value otherwise.
func (o *UserPlaneEventReport) GetQosMonReports() []QosMonitoringReport {
	if o == nil || o.QosMonReports == nil {
		var ret []QosMonitoringReport
		return ret
	}
	return *o.QosMonReports
}

// GetQosMonReportsOk returns a tuple with the QosMonReports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPlaneEventReport) GetQosMonReportsOk() (*[]QosMonitoringReport, bool) {
	if o == nil || o.QosMonReports == nil {
		return nil, false
	}
	return o.QosMonReports, true
}

// HasQosMonReports returns a boolean if a field has been set.
func (o *UserPlaneEventReport) HasQosMonReports() bool {
	if o != nil && o.QosMonReports != nil {
		return true
	}

	return false
}

// SetQosMonReports gets a reference to the given []QosMonitoringReport and assigns it to the QosMonReports field.
func (o *UserPlaneEventReport) SetQosMonReports(v []QosMonitoringReport) {
	o.QosMonReports = &v
}

func (o UserPlaneEventReport) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["event"] = o.Event
	}
	if o.AccumulatedUsage != nil {
		toSerialize["accumulatedUsage"] = o.AccumulatedUsage
	}
	if o.FlowIds != nil {
		toSerialize["flowIds"] = o.FlowIds
	}
	if o.AppliedQosRef != nil {
		toSerialize["appliedQosRef"] = o.AppliedQosRef
	}
	if o.QosMonReports != nil {
		toSerialize["qosMonReports"] = o.QosMonReports
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *UserPlaneEventReport) UnmarshalJSON(bytes []byte) (err error) {
	varUserPlaneEventReport := _UserPlaneEventReport{}

	if err = json.Unmarshal(bytes, &varUserPlaneEventReport); err == nil {
		*o = UserPlaneEventReport(varUserPlaneEventReport)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "event")
		delete(additionalProperties, "accumulatedUsage")
		delete(additionalProperties, "flowIds")
		delete(additionalProperties, "appliedQosRef")
		delete(additionalProperties, "qosMonReports")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserPlaneEventReport struct {
	value *UserPlaneEventReport
	isSet bool
}

func (v NullableUserPlaneEventReport) Get() *UserPlaneEventReport {
	return v.value
}

func (v *NullableUserPlaneEventReport) Set(val *UserPlaneEventReport) {
	v.value = val
	v.isSet = true
}

func (v NullableUserPlaneEventReport) IsSet() bool {
	return v.isSet
}

func (v *NullableUserPlaneEventReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserPlaneEventReport(val *UserPlaneEventReport) *NullableUserPlaneEventReport {
	return &NullableUserPlaneEventReport{value: val, isSet: true}
}

func (v NullableUserPlaneEventReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserPlaneEventReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


